function buttonPress() {alert("You shouldn't be here..")
alert("I warned you not to click the button")
alert("And you did..")
alert("Just exit the webpage and we can move on..")
alert("Oi! Stop!")
alert("Stop pressing OK!")
alert("Im not gonna let you continue!")
alert("...")
alert("...")
alert("...")
alert("...")
alert("...")
alert("Stop!")
alert("Im actually serious, dont!")
alert("You are not giving up, are you?")
alert("Do you really want to see?")
alert("Alright fine but im telling you now its not good..")
alert("here we go..")
window.location.href = "https://youtu.be/xvFZjo5PgG0";
}